### ISSUE TITLE
What is the kind of license for this?

### ISSUE THREAD

**Issue by 0ctopus13prime** [nanosai/rion-ops-java#19]
Hello, it looks promising for my on going project in the work and hope to test this if the license fit for my situation
Is it Apache or Mit?
Thanks in advance

**Comment by jjenkov** [comment]
We haven't actually decided yet - but I think we are in favour of the Apache 2 License.

**Comment by 0ctopus13prime** [comment]
Cool!
Then may I know when the decision will be made?
In the mean time, I'm going to perform some tests and wait to see what kinds of the license will be.

**Comment by jjenkov** [comment]
We have decided to release RION Ops under the Apache License 2.0

**Comment by 0ctopus13prime** [comment]
Thank you for the update :)
