### ISSUE TITLE
UTF8 not working correctly

### ISSUE THREAD

**Issue by hvbtup** [nanosai/rion-ops-java#3]
While testing I noticed that UTF8 is not working correctly.
The reader uses just the new String(byte[]) constructor without specifying the encoding.

The solution is obvious:
I had to change several places in the RionReader and RionWriter code.

Just to give one example:

    public String readKeyShortAsUtf8String(){
        if(fieldLengthLength == 0) {
			return null;
		}

		return new String(source, index, fieldLength, UTF8_CHARSET);
    }

Just look for new String(...) calls in the code.

In the reader, look for occurences of utf8Bytes.
I simplified these like this (for example, inside the writeUtf8(String value) method):

	byte[] utf8Bytes = value.getBytes(UTF8_CHARSET);

**Comment by jjenkov** [comment]
Strange... I am fully aware that the charset must be explicitly set when creating a Java String from UTF-8 encoded bytes... I wonder why I would have forgotten to do that... ?!?

Anyways, it's an easy fix, and I will get it done soon!

**Comment by jjenkov** [comment]
This has been fixed now - in version 0.5.3

**Comment by jjenkov** [comment]
v. 0.5.3 has now been released
